### ISSUE TITLE
Decoding into an object fails if any column has NULL value

### ISSUE THREAD

**Issue by rafiki270** [vapor/mysql#116]
Model User
```swift
    public var id: ID?
    public var firstname: String
    public var lastname: String
    public var email: String
    public var password: String?
    public var token: String?
    public var expires: Date?
    public var registered: Date
```

I had inserted an object that has `token` and 'expires` as NULL and decode fails with a message `The received packet was invalid`

**Comment by Joannis** [comment]
This should be fixed since a few days, let me know if it's not :)

**Comment by MihaelIsaev** [comment]
It is still fails on Vapor 3 beta
`The packet could not be parsed into valid a response`

**Comment by MihaelIsaev** [comment]
It’s easy to reproduce

Just add `var someText: String?` to `Todo`’s model (in standart todo template, but with fluentmysql)

Then send `POST` to `http://localhost/todos` with the following JSON `{"title": "hello" }` it will create new row in `todos` table with nulled `someText`
Then just do `GET` to `http://localhost:8080/todos/` and you’ll get `Oops: The packet could not be parsed into valid a response` error

**Comment by Joannis** [comment]
I'm suspecting that the NULL bitmap has a different endianness than is currently implemented.

**Comment by Joannis** [comment]
I'm suspecting that the NULL bitmap has a different endianness

**Comment by tanner0101** [comment]
Sorry, closed this thinking it must have been fixed already. Somehow wasn't. Fixed by #133

**Comment by tanner0101** [comment]
_Now_ it's fixed. :)
